// this comtains the data we are gonna for AboutMe component and slider component

export const AboutData = [
  {
    count: 1,
    title: "Front-end Developer",
    img: "/second.svg",
    array: [
      "HTML",
      "CSS/SASS",
      "TailwindCSS/Bootstrap",
      "JavaScript (ES6)",
      "ReactJS",
      "NextJS",
      "REST API / GraphQL",
    ],
  },
  {
    count: 2,
    title: "Back-end Developer",
    img: "/third.svg",
    demo: "https://yasakura-vanillajs-1.netlify.app/",
    github:'https://github.com/yutaasakura96/vanilla-js-project-1',
    array: [
      "Ruby",
      "Ruby on Rails",
      "PostgreSQL",
      "Next.js (API)",
    ],
  },
  {
    count: 3,
    title: "UI / UX Designer",
    img: "/first.svg",
    array: [
      "Wireframe",
      "Prototyping",
      "Figma",
      "Canva",
      "Excalidraw",
      "Coolors",
      "FontPair",
    ],
  },
  {
    count: 4,
    title: "Tools",
    img: "/sisxth.svg",
    array: [
      "VSCode",
      "Git / Github",
      "Bash / Powershell",
      "NPM / Yarn",
      "Vercel / Heroku / Netlify",
      "Postman / Insomnia",
    ],
  },
];

// this is for the slider
export const DataArray = [
  {
    title: " AI powered CRM-like tool",
    name: "Personal Relations Manager",
    demo: "https://www.theprm.tech/",
    github:'https://github.com/jpblicer/PRM',
    des: "Personal Relationship Manager is an AI powered CRM-like tool aimed at individual mobile users who want to further their career.This Application was developed as part of a 2 week challenge from inception to completition as part of the Tokyo Le Wagon bootcamp.",
    des1: "Login Credentials for the live demo: user: admin@admin.com pw: adminadmin",
    images: ["/prm1.png"],
    tech: ['Ruby', 'Ruby on Rails', 'Javascript', 'OpenAi API', 'PostgreSQL', 'Bootstrap', 'SASS', 'HTML'],
  },
  {
    title: "Desktop first fully responsive MPA",
    name: "Code and Create",
    demo: "https://yasakura-vanillajs-1.netlify.app/",
    github:'https://github.com/yutaasakura96/vanilla-js-project-1',
    des: "This project is a fully responsive, multi-page web app created using HTML, CSS, and vanilla JavaScript. It features a modern design with dynamic content and advanced CSS techniques, enhancing both the look and functionality of the site.",
    des1: "",
    images: ["/codeandcreate.png", "/codeandcreatefull.png"],
    tech: ['Javascript', 'CSS', 'HTML'],
  },
  {
    title: "Fully responsive desktop SPA",
    name: "Omnifood Project",
    demo: "https://omnifood-yasakura.netlify.app/",
    github:'https://github.com/yutaasakura96/Project-Omnifood',
    des: "Omnifood is a fictional company specializing in AI-based meal subscriptions, and this single-page website highlights both responsive design and advanced CSS techniques.",
    des1: "",
    images: ["/projectomnifood.png", "/omnifoodfull.png"],
    tech: ['Javascript', 'CSS', 'HTML'],
  },
  {
    title: "Fictional real estate website",
    name: "Nexter Project ",
    demo: "https://yasakura-nexterproject.netlify.app/",
    github:'https://github.com/yutaasakura96/Nexter-Project',
    des: "Nexter is a fictional real estate website designed to showcase luxurious homes and provide users with a seamless home-buying experience. This project demonstrates advanced CSS Grid and SCSS techniques, resulting in a fully responsive layout with rich features and an elegant design.",
    des1: "",
    images: ["/nexterproject.png", "/nexterfull.png"],
    tech: ['Javascript', 'SASS', 'HTML'],
  },
  {
    title: "Fictional tour company website",
    name: "Natours Project",
    demo: "https://natoursproject-yasakura.netlify.app/",
    github:'https://github.com/yutaasakura96/Natours-Project',
    des: "Natours is a fictional tour company website designed to inspire people to explore the natural world through exciting adventures. This project is built using advanced SCSS techniques, showcasing features like animations, color management, responsive design with Sass mixins, and modern web design practices.",
    images: ["/natoursproject.png", "/natoursfull.png"],
    tech: ['Javascript', 'SASS', 'HTML'],
  },
];
